version: '3.8'
services:
   web:
       build:
         context: .
         dockerfile: Dockerfile
       depends_on:
         - postgres
       restart: always
       command: sh -c "python manage.py runserver 0.0.0.0:8000"
#       command: sh -c "python manage.py makemigrations &&
#         python manage.py migrate &&
#         python manage.py createsuperuser --username=admin --email=test@email.com --no-input &&
#         python manage.py runserver 0.0.0.0:8000"
       ports:
           - 8000:8000
       env_file:
         - ./server_for_friends/.env
   postgres:
      image: postgres:13.3
      env_file:
        - ./server_for_friends/.env
      volumes:
        - ./pgdata:/var/lib/postgresql/pgdata
      ports:
        - 5432:5432