version: '3.8'
services:
   web:
       build:
         context: .
         dockerfile: Dockerfile
       restart: always
       depends_on:
         - postgres
       command: gunicorn server_for_friends.wsgi:application --bind 0.0.0.0:8000
       expose:
         - 8000
       volumes:
         - static_volume:/service/static
         - media_volume:/service/media
       env_file:
         - ./server_for_friends/.env
   postgres:
      image: postgres:13.3
      env_file:
        - ./server_for_friends/.env
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - 5432:5432
   nginx:
      build: ./nginx
      volumes:
        - static_volume:/service/static
        - media_volume:/service/media
      ports:
        - 80:80
      depends_on:
        - web
volumes:
  static_volume:
  media_volume: