# Generated by Django 4.2.1 on 2023-05-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name': 'Связь'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
